fix

diff --git a/.github/workflows/auto-release-merge.yml b/.github/workflows/auto-release-merge.yml
--- a/.github/workflows/auto-release-merge.yml
+++ b/.github/workflows/auto-release-merge.yml
@@ -7,39 +7,28 @@ on:
   workflow_dispatch: 
     
 jobs:
-  get-branch-list:
+  merge-branches:
     runs-on: ubuntu-latest
-    outputs:
-      branch_list: ${{ steps.branch_list.outputs.branch_list }}
     steps:
-      - name: Create branch list
-        id: branch_list
-        run: |
-          list=$(echo "${{ vars.MERGE_BRANCHES }}" | awk NF | tr '\n' ',')
-
-          echo "branch_list=[ $list ]" >> $GITHUB_OUTPUT
-
-  merge-release-branches:
-    needs: get-branch-list
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        value: ${{ fromJson(needs.get-branch-list.outputs.branch_list) }}
-    steps:
-      - name: Checkout
+      - name: Checkout code
         uses: actions/checkout@v3
         with:
           fetch-depth: '0'
-
       - name: Set e-mail and username
         run: |
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "GitHub Action"
-        
-      - name: Merge branch
+      - name: Merge branches in sequence
         run: |
-          git fetch origin release/${{ matrix.value }}
-          git checkout release/${{ matrix.value }}
-          git merge ${{ github.ref_name }}
-          git push origin release/${{ matrix.value }}
+          branches=(${{ vars.MERGE_BRANCHES }})
+          for ((i = 0; i < ${#branches[@]} - 1; i++)); do
+            current="${branches[i]}"
+            next="${branches[i+1]}"
+            
+            echo "Merging $current into $next"
+            
+            git fetch origin "$next"
+            git checkout "$next"
+            git merge "$current" || { echo "Merging failed, stopping..."; exit 1; }
+            git push origin "$next"
+          done
